import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  messagesContainer: {
    flex: 1,
  },
  messagesContent: {
    padding: 12,
    paddingBottom: 4,
  },
  messageContainer: {
    flexDirection: 'row',
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  userMessage: {
    justifyContent: 'flex-end',
  },
  aiMessage: {
    justifyContent: 'flex-start',
  },
  aiAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#4A90D9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  aiAvatarText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  aiAvatarImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 8,
  },
  userAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#67C23A',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  userAvatarText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  userAvatarImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginLeft: 8,
  },
  messageBubble: {
    maxWidth: '72%',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 1,
  },
  userBubble: {
    backgroundColor: '#4A90D9',
    borderBottomRightRadius: 6,
  },
  aiBubble: {
    backgroundColor: '#fff',
    borderBottomLeftRadius: 6,
  },
  senderName: {
    fontSize: 12,
    color: '#4A90D9',
    marginBottom: 4,
    fontWeight: '600',
  },
  messageText: {
    fontSize: 16,
    color: '#333',
    lineHeight: 22,
  },
  userMessageText: {
    color: '#fff',
  },
  emojiMessage: {
    width: 120,
    height: 120,
    borderRadius: 12,
  },
  messageFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: 4,
  },
  messageTime: {
    fontSize: 11,
    color: '#999',
  },
  userMessageTime: {
    color: 'rgba(255,255,255,0.7)',
  },
  voiceButton: {
    marginLeft: 8,
    padding: 2,
  },
  typingContainer: {
    padding: 8,
    paddingHorizontal: 16,
  },
  typingText: {
    fontSize: 13,
    color: '#999',
    fontStyle: 'italic',
  },
  moreMenu: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 16,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    gap: 16,
  },
  moreMenuItem: {
    alignItems: 'center',
    width: 64,
  },
  moreMenuIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  moreMenuText: {
    fontSize: 11,
    color: '#666',
    marginTop: 4,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  attachButton: {
    padding: 6,
  },
  input: {
    flex: 1,
    marginHorizontal: 8,
    padding: 10,
    backgroundColor: '#f5f5f5',
    borderRadius: 20,
    fontSize: 16,
    maxHeight: 100,
  },
  sendButton: {
    padding: 8,
  },
  sendButtonDisabled: {
    opacity: 0.5,
  },
  emojiPanel: {
    backgroundColor: '#fff',
    height: 320,
  },
  emojiHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  emojiTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  emojiHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  emojiSettingsBtn: {
    padding: 4,
  },
  emojiCloseBtn: {
    padding: 4,
  },
  emojiTabs: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingHorizontal: 8,
  },
  emojiTab: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  emojiTabActive: {
    borderBottomWidth: 2,
    borderBottomColor: '#4A90D9',
  },
  emojiTabText: {
    fontSize: 13,
    color: '#666',
  },
  emojiTabTextActive: {
    color: '#4A90D9',
    fontWeight: '500',
  },
  addPackBtn: {
    padding: 8,
    marginLeft: 'auto',
  },
  emojiGrid: {
    padding: 8,
  },
  emojiItem: {
    flex: 1,
    aspectRatio: 1,
    margin: 4,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#f0f0f0',
  },
  emojiImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  emojiClose: {
    position: 'absolute',
    top: 8,
    right: 8,
  },
  emptyEmojiContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  emptyEmojiText: {
    fontSize: 14,
    color: '#999',
    marginTop: 8,
  },
  goManageBtn: {
    marginTop: 12,
    paddingHorizontal: 20,
    paddingVertical: 8,
    backgroundColor: '#4A90D9',
    borderRadius: 16,
  },
  goManageBtnText: {
    color: '#fff',
    fontSize: 14,
  },
  quickRepliesPanel: {
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    padding: 16,
  },
  quickRepliesTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
    marginBottom: 12,
  },
  quickRepliesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  quickReplyItem: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#f5f5f5',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#eee',
  },
  quickReplyText: {
    fontSize: 14,
    color: '#333',
  },
  quickReplyClose: {
    position: 'absolute',
    top: 8,
    right: 8,
  },
  backgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    opacity: 0.3,
  },
  headerButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  membersList: {
    padding: 16,
  },
  memberItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  memberAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  memberAvatarPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },
  memberAvatarText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  memberInfo: {
    marginLeft: 12,
    flex: 1,
  },
  memberName: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
  },
  memberPersonality: {
    fontSize: 13,
    color: '#999',
    marginTop: 2,
  },
  groupMembersContainer: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  groupMembersHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  groupMembersTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  avatarPreviewOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarPreviewContainer: {
    alignItems: 'center',
  },
  avatarPreviewImage: {
    width: 200,
    height: 200,
    borderRadius: 100,
  },
  avatarPreviewPlaceholder: {
    width: 200,
    height: 200,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarPreviewText: {
    color: '#fff',
    fontSize: 64,
    fontWeight: 'bold',
  },
  avatarPreviewName: {
    color: '#fff',
    fontSize: 18,
    marginTop: 16,
    fontWeight: '500',
  },
  imageOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullImage: {
    width: '100%',
    height: '80%',
  },
  imageCloseBtn: {
    position: 'absolute',
    top: 50,
    right: 20,
  },
  loadingMore: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 12,
    gap: 8,
  },
  loadingMoreText: {
    fontSize: 13,
    color: '#999',
  },
  imagePreviewOverlay: {
    flex: 1,
    backgroundColor: '#000',
  },
  imagePreviewContainer: {
    flex: 1,
  },
  imagePreviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    paddingTop: 50,
    backgroundColor: '#fff',
  },
  imagePreviewTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  imagePreviewSend: {
    fontSize: 16,
    color: '#4A90D9',
    fontWeight: '600',
  },
  imagePreview: {
    flex: 1,
    width: '100%',
  },
  imageCommentContainer: {
    backgroundColor: '#fff',
    padding: 16,
  },
  imageCommentInput: {
    backgroundColor: '#f5f5f5',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 15,
    maxHeight: 80,
  },
  pendingContainer: {
    backgroundColor: '#fff',
    padding: 10,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  pendingPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  pendingImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
  },
  pendingClose: {
    padding: 4,
  },
  pendingHint: {
    fontSize: 12,
    color: '#999',
    marginTop: 6,
  },
  newMessageHint: {
    position: 'absolute',
    bottom: 80,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#4A90D9',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  newMessageHintText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '500',
  },
  musicCardList: {
    gap: 6,
  },
  musicCardScroll: {
    flexDirection: 'row',
    marginVertical: 4,
  },
  musicCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8f8f8',
    borderRadius: 10,
    padding: 8,
    gap: 10,
  },
  musicCardCover: {
    width: 44,
    height: 44,
    borderRadius: 6,
    backgroundColor: '#e0e0e0',
  },
  musicCardInfo: {
    flex: 1,
  },
  musicCardName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  musicCardArtist: {
    fontSize: 12,
    color: '#999',
    marginTop: 1,
  },
  musicCardPlay: {
    padding: 4,
  },
  musicSearchOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  musicSearchContainer: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: '80%',
    paddingBottom: 20,
  },
  musicSearchHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  musicSearchTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  musicSearchInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    gap: 8,
  },
  musicSearchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 10,
    fontSize: 15,
    color: '#333',
  },
  musicSearchBtn: {
    backgroundColor: '#4A90D9',
    borderRadius: 8,
    padding: 10,
    paddingHorizontal: 14,
  },
  sendToChatBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#67C23A',
    borderRadius: 8,
    padding: 10,
    marginHorizontal: 12,
    marginBottom: 8,
    gap: 6,
  },
  sendToChatBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
  },
  musicResultList: {
    paddingHorizontal: 12,
  },
  musicResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    gap: 10,
  },
  musicResultCover: {
    width: 44,
    height: 44,
    borderRadius: 6,
    backgroundColor: '#e0e0e0',
  },
  musicResultInfo: {
    flex: 1,
  },
  musicResultName: {
    fontSize: 15,
    color: '#333',
    fontWeight: '500',
  },
  musicResultArtist: {
    fontSize: 13,
    color: '#999',
    marginTop: 1,
  },
  musicSearchEmpty: {
    alignItems: 'center',
    padding: 40,
  },
  musicSearchEmptyText: {
    fontSize: 14,
    color: '#999',
    marginTop: 8,
  },
});
